Repository onekey-sec/unblob, pull requests merged in 2022-06, with the labels that each got.

#377 nix: fix nix-shell using dependencies from wheels
  nix/poetry/default.nix
Labels: enhancement

#380 elf: fix kernel initramfs extraction padding calculation
  unblob/handlers/executable/elf.py
Labels: bug

#396 Explicitly set LIEF logging level.
  unblob/handlers/executable/elf.py
Labels: enhancement

#398 add EFI files to skip list until we have a proper handler for it.
  unblob/processing.py
Labels: enhancement

#397 Improve cramfs CRC check
  tests/integration/filesystem/cramfs/big_endian/__input__/fruits.crc_swap.cramfs_be
  tests/integration/filesystem/cramfs/big_endian/__input__/fruits.old.cramfs_be
  tests/integration/filesystem/cramfs/big_endian/__output__/fruits.crc_swap.cramfs_be_extract/apple.txt
  tests/integration/filesystem/cramfs/big_endian/__output__/fruits.crc_swap.cramfs_be_extract/cherry.txt
  tests/integration/filesystem/cramfs/big_endian/__output__/fruits.old.cramfs_be_extract/apple.txt
  tests/integration/filesystem/cramfs/big_endian/__output__/fruits.old.cramfs_be_extract/cherry.txt
  tests/integration/filesystem/cramfs/little_endian/__input__/fruits.crc_swap.cramfs_le
  tests/integration/filesystem/cramfs/little_endian/__input__/fruits.old.cramfs_le
  tests/integration/filesystem/cramfs/little_endian/__output__/fruits.crc_swap.cramfs_le_extract/apple.txt
  tests/integration/filesystem/cramfs/little_endian/__output__/fruits.crc_swap.cramfs_le_extract/cherry.txt
  tests/integration/filesystem/cramfs/little_endian/__output__/fruits.old.cramfs_le_extract/apple.txt
  tests/integration/filesystem/cramfs/little_endian/__output__/fruits.old.cramfs_le_extract/cherry.txt
  unblob/handlers/filesystem/cramfs.py
Labels: format:filesystem

#395 Add ZSTD compression format
  .github/actions/setup-dependencies/action.yml
  Dockerfile
  default.nix
  tests/integration/compression/zstd/__input__/lorem.both.zstd
  tests/integration/compression/zstd/__input__/lorem.prefixed.zstd
  tests/integration/compression/zstd/__input__/lorem.suffixed.zstd
  tests/integration/compression/zstd/__input__/lorem.truncated.zstd
  tests/integration/compression/zstd/__input__/lorem.zstd
  tests/integration/compression/zstd/__output__/lorem.both.zstd_extract/0-4.unknown
  tests/integration/compression/zstd/__output__/lorem.both.zstd_extract/2628-2632.unknown
  tests/integration/compression/zstd/__output__/lorem.both.zstd_extract/4-2628.zstd
  tests/integration/compression/zstd/__output__/lorem.both.zstd_extract/4-2628.zstd_extract/4-2628
  tests/integration/compression/zstd/__output__/lorem.prefixed.zstd_extract/0-4.unknown
  tests/integration/compression/zstd/__output__/lorem.prefixed.zstd_extract/4-2628.zstd
  tests/integration/compression/zstd/__output__/lorem.prefixed.zstd_extract/4-2628.zstd_extract/4-2628
  tests/integration/compression/zstd/__output__/lorem.suffixed.zstd_extract/0-2624.zstd
  tests/integration/compression/zstd/__output__/lorem.suffixed.zstd_extract/0-2624.zstd_extract/0-2624
  tests/integration/compression/zstd/__output__/lorem.suffixed.zstd_extract/2624-2628.unknown
  tests/integration/compression/zstd/__output__/lorem.truncated.zstd_extract/.gitkeep
  tests/integration/compression/zstd/__output__/lorem.zstd_extract/lorem
  unblob/handlers/__init__.py
  unblob/handlers/compression/zstd.py
Labels: enhancement, format:compression
