Repository onekey-sec/unblob, pull requests merged in 2023-01, with the labels that each got.

#488 jffs2: ignore CRC for inaccurate node types
  unblob/handlers/filesystem/jffs2.py
Labels: bug, format:filesystem

#487 Allow carving only
  unblob/cli.py
  unblob/processing.py
Labels: enhancement

#490 Update documentation to explain how to perform a system wide install from source
  docs/installation.md
Labels: documentation

#491 delete empty _extract directories when an ExtractError is raised.
  tests/integration/executable/elf/elf32/__output__/sample_32_be.elf_extract/13-5877.elf32_extract/.gitkeep
  tests/integration/executable/elf/elf32/__output__/sample_32_le.elf_extract/13-15601.elf32_extract/.gitkeep
  tests/integration/executable/elf/elf64/__output__/hellomod.sha1.brokensig.ko_extract/0-215704.elf64_extract/.gitkeep
  tests/integration/executable/elf/elf64/__output__/hellomod.sha1.extra.ko_extract/0-216459.elf64_extract/.gitkeep
  tests/integration/executable/elf/elf64/__output__/hellomod.sha1.nofooter.ko_extract/0-215704.elf64_extract/.gitkeep
  tests/integration/executable/elf/elf64/__output__/sample_64_be.elf_extract/13-67741.elf64_extract/.gitkeep
  tests/integration/executable/elf/elf64/__output__/sample_64_le.elf_extract/13-16709.elf64_extract/.gitkeep
  unblob/processing.py
Labels: enhancement

#492 Improved unblob documentation
  default.nix
  docs/ArtegraSans-Regular.ttf
  docs/api.md
  docs/extra.css
  docs/index.md
  docs/publications.md
  docs/unblob_architecture.webp
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#499 fix(typing): Remove int restriction from decode_int
  unblob/file_utils.py
Labels: python
