Repository onekey-sec/unblob, pull requests merged in 2023-11, with the labels that each got.

#675 move e2fsprogs dependency to onekey maintained fork.
  docs/installation.md
  overlay.nix
  unblob/install-deps.sh
Labels: documentation, format:filesystem, dependencies

#679 plugins: `is_dir` was always true
  unblob/plugins.py
Labels: bug

#681 add unlink function to FileSystem API.
  tests/test_file_utils.py
  unblob/file_utils.py
Labels: enhancement
