Repository onekey-sec/unblob, pull requests merged in 2023-09, with the labels that each got.

#651 handle a potential race condition when deleting log file.
  unblob/logging.py
  unblob/testing.py
Labels: bug

#632 fix(handler): handle truncated FAT images
  nix/_sources/generated.json
  nix/_sources/generated.nix
  nix/pyfatfs/default.nix
  nix/unblob/default.nix
  nvfetcher.toml
  overlay.nix
  poetry.lock
  pyproject.toml
  tests/handlers/filesystem/test_fat.py
  tests/integration/filesystem/fat/fat12/__input__/cherry.truncated.fat12
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/0-28160.fat
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/0-28160.fat_extract/cherry1.txt
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/0-28160.fat_extract/cherry2.txt
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/0-28160.fat_extract/cherry3.txt
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/0-28160.fat_extract/cherry4.txt
  tests/integration/filesystem/fat/fat12/__output__/cherry.truncated.fat12_extract/28160-32768.unknown
  tests/integration/filesystem/fat/fat16/__input__/banana.truncated.fat16
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/0-28160.fat
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/0-28160.fat_extract/banana1.txt
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/0-28160.fat_extract/banana2.txt
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/0-28160.fat_extract/banana3.txt
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/0-28160.fat_extract/banana4.txt
  tests/integration/filesystem/fat/fat16/__output__/banana.truncated.fat16_extract/28160-32768.unknown
  tests/integration/filesystem/fat/fat32/__input__/banana.truncated.fat32
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/0-551424.fat
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/0-551424.fat_extract/banana1.txt
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/0-551424.fat_extract/banana2.txt
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/0-551424.fat_extract/banana3.txt
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/0-551424.fat_extract/banana4.txt
  tests/integration/filesystem/fat/fat32/__output__/banana.truncated.fat32_extract/551424-2097152.unknown
  unblob/file_utils.py
  unblob/handlers/filesystem/fat.py
  vulture_whitelist.py
Labels: enhancement, format:filesystem

#652 update wiki
  docs/formats.md
  docs/installation.md
  docs/publications.md
Labels: documentation

#658 chore(deps): do not use SemVer dependency specification for CalVer dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#657 fix(handlers): fix extfs handler for samples with spaces in their names.
  unblob/handlers/filesystem/extfs.py
Labels: bug, format:filesystem
