Repository onekey-sec/unblob, pull requests merged in 2024-12, with the labels that each got.

#1013 feat(ci): use macos-14 in build-nix.
  .github/workflows/build-nix.yml
Labels: CI/CD

#597 Experimental Landlock based sandboxing
  tests/test_cli.py
  tests/test_sandbox.py
  unblob/cli.py
  unblob/pool.py
  unblob/processing.py
  unblob/sandbox.py
  unblob/signals.py
  unblob/testing.py
Labels: enhancement, dependencies

#1008 Drop python 3.8 support
  .github/actions/setup-dependencies/action.yml
  .github/workflows/documentation.yml
  .github/workflows/run-tests.yml
  Dockerfile
  docs/development.md
  poetry.lock
  pyproject.toml
  tests/test_cli.py
  tests/test_file_utils.py
  tests/test_handlers.py
  tests/test_processing.py
  tests/test_report.py
  unblob/cli.py
  unblob/dependencies.py
  unblob/extractor.py
  unblob/extractors/command.py
  unblob/file_utils.py
  unblob/finder.py
  unblob/handlers/archive/cpio.py
  unblob/handlers/archive/netgear/trx.py
  unblob/handlers/archive/xiaomi/hdr.py
  unblob/handlers/compression/compress.py
  unblob/handlers/compression/gzip.py
  unblob/handlers/compression/xz.py
  unblob/handlers/filesystem/romfs.py
  unblob/handlers/filesystem/squashfs.py
  unblob/handlers/filesystem/yaffs.py
  unblob/hookspecs.py
  unblob/iter_utils.py
  unblob/logging.py
  unblob/models.py
  unblob/plugins.py
  unblob/pool.py
  unblob/processing.py
  unblob/report.py
  unblob/sandbox.py
Labels: documentation, dependencies, python, CI/CD
