Repository onekey-sec/unblob, pull requests merged in 2024-01, with the labels that each got.

#694 add docker container scanning with grype.
  .github/workflows/build-publish-image.yml
Labels: dependencies

#693 Extend default skip magic rather than overwrite it.
  tests/test_cli.py
  unblob/cli.py
  unblob/processing.py
Labels: enhancement

#700 fix(handler): lower invalid checksum logs in tar handler from error to debug
  unblob/handlers/archive/tar.py
Labels: enhancement, format:archive

#702 fix(handler): extend extfs valid states to 0, 1, and 2.
  tests/integration/filesystem/extfs/__input__/ext2.1024.nullstate.img
  tests/integration/filesystem/extfs/__input__/ext3.1024.nullstate.img
  tests/integration/filesystem/extfs/__input__/ext4.1024.nullstate.img
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/0-524288.extfs
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/0-524288.extfs_extract/apple.txt
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/0-524288.extfs_extract/banana.txt
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/0-524288.extfs_extract/cherry.txt
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/0-524288.extfs_extract/lost+found/.gitkeep
  tests/integration/filesystem/extfs/__output__/ext2.1024.nullstate.img_extract/524288-524289.padding
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/0-524288.extfs
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/0-524288.extfs_extract/apple.txt
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/0-524288.extfs_extract/banana.txt
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/0-524288.extfs_extract/cherry.txt
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/0-524288.extfs_extract/lost+found/.gitkeep
  tests/integration/filesystem/extfs/__output__/ext3.1024.nullstate.img_extract/524288-524289.padding
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/0-524288.extfs
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/0-524288.extfs_extract/apple.txt
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/0-524288.extfs_extract/banana.txt
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/0-524288.extfs_extract/cherry.txt
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/0-524288.extfs_extract/lost+found/.gitkeep
  tests/integration/filesystem/extfs/__output__/ext4.1024.nullstate.img_extract/524288-524289.padding
  unblob/handlers/filesystem/extfs.py
Labels: bug, format:filesystem

#706 fix(handler): fix UBI PEB size calculation.
  tests/test_iter_utils.py
  unblob/iter_utils.py
Labels: bug, format:filesystem

#707 chore(deps): add dependabot version updates
  .github/dependabot.yml
Labels: enhancement, dependencies

#721 fix(handler): increase tar handler debug log verbosity level.
  unblob/handlers/archive/tar.py
Labels: enhancement, format:archive

#720 fix(processing): do not process Java module image files by default.
  unblob/processing.py
Labels: enhancement

#723 parser: support regex style begin-end anchors (`^`, `$`)
  docs/development.md
  tests/test_parser.py
  unblob/parser.py
Labels: enhancement

#739 fix(ci): use unique artifacts names
  .github/workflows/build-publish-image.yml
Labels: bug, github_actions

#741 feat(ci): use Apple M1 runner in build-nix.
  .github/workflows/build-nix.yml
Labels: enhancement
