Repository onekey-sec/unblob, pull requests merged in 2024-02, with the labels that each got.

#722 add search_chunks fuzzing with atheris
  fuzzing/search_chunks_fuzzer.py
  poetry.lock
  pyproject.toml
Labels: fuzzing

#743 Fix #724. build: Add darwin aarch64 to supported architectures
  flake.nix
  overlay.nix
Labels: enhancement

#749 chore(deps): upgrade pyright to 1.1.349
  poetry.lock
  pyproject.toml
  unblob/handlers/compression/_gzip_reader.py
Labels: dependencies

#738 chore(deps): upgrade pytest-cov to 4.1.0, pytest to 8.0.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#762 chore(ci): release version tagged container images.
  .github/workflows/build-publish-image.yml
Labels: enhancement

#755 fix(models): adapt chunk's contains() definition.
  tests/test_models.py
  unblob/models.py
Labels: bug

#765 fix(squashfs): fixed end_of_data_offset calculation
  unblob/handlers/filesystem/squashfs.py
Labels: bug, format:filesystem

#773 fix(handlers): handle dangling symlinks in MultiFile handlers.
  tests/integration/archive/sevenzip/__input__/multi-sevenzip-dangling-symlinks.tar
  tests/integration/archive/sevenzip/__output__/multi-sevenzip-dangling-symlinks.tar_extract/dangling-symlink.7z.001
  tests/integration/archive/sevenzip/__output__/multi-sevenzip-dangling-symlinks.tar_extract/dangling-symlink.7z.002
  tests/integration/archive/sevenzip/__output__/multi-sevenzip-dangling-symlinks.tar_extract/dangling-symlink.7z.003
  tests/integration/compression/gzip/__input__/multi-gzip-dangling-symlinks.tar
  tests/integration/compression/gzip/__output__/multi-gzip-dangling-symlinks.tar_extract/dangling-symlink.gz.a
  tests/integration/compression/gzip/__output__/multi-gzip-dangling-symlinks.tar_extract/dangling-symlink.gz.b
  tests/integration/compression/gzip/__output__/multi-gzip-dangling-symlinks.tar_extract/dangling-symlink.gz.c
  unblob/handlers/archive/sevenzip.py
  unblob/handlers/compression/gzip.py
Labels: bug, format:archive, format:compression

#775 Fix SafeTarFile symlinks extraction
  tests/integration/archive/tar/__input__/symlinks.tar
  tests/integration/archive/tar/__output__/absolute.tar_extract/absolute/absolute-symlink
  tests/integration/archive/tar/__output__/absolute.tar_extract/absolute/link_to_etc_shadow
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/bin/busybox
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/sbin/cp
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/sbin/find
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/sbin/ln
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/sbin/ls
  tests/integration/archive/tar/__output__/symlinks.tar_extract/test/sbin/mv
  tests/test_file_utils.py
  unblob/handlers/archive/_safe_tarfile.py
Labels: bug, format:archive

#783 chore(ci): tag merged docker image with version info.
  .github/workflows/build-publish-image.yml
Labels: enhancement
