Repository onekey-sec/unblob, pull requests merged in 2025-01, with the labels that each got.

#1041 fix: overwrite report file rather than unlink it when -f option is set
  unblob/processing.py
Labels: bug, python

#1047 ci: fix setting up arm emulation on Ubuntu Noble
  .github/workflows/build-nix.yml
Labels: bug, CI/CD

#1067 Revert "chore(deps): update python docker tag to v3.13"
  Dockerfile
Labels: dependencies

#1083 chore: help pyright 1.1.392 figure out the correct typing of pairwise
  unblob/iter_utils.py
Labels: python

#1084 Pyright enable standard type checking mode
  pyproject.toml
  unblob/extractors/command.py
  unblob/file_utils.py
  unblob/handlers/compression/_gzip_reader.py
  unblob/models.py
Labels: enhancement, python
