Repository onekey-sec/unblob, pull requests merged in 2025-03, with the labels that each got.

#1144 Revert "add intel flashrom to magic skip list"
  python/unblob/processing.py
Labels: enhancement, format:executable

#1152 fix(processing): adapt is_padding to fix potential MemoryError
  python/unblob/processing.py
Labels: bug, enhancement

#1143 feat(handler): add geom_uzip handler
  overlay.nix
  pyproject.toml
  python/unblob/handlers/__init__.py
  python/unblob/handlers/compression/uzip.py
  tests/integration/compression/uzip/lzma/__input__/myfs.img.ulzma
  tests/integration/compression/uzip/lzma/__output__/myfs.img.ulzma_extract/0-59316.uzip
  tests/integration/compression/uzip/lzma/__output__/myfs.img.ulzma_extract/0-59316.uzip_extract/0-59316
  tests/integration/compression/uzip/lzma/__output__/myfs.img.ulzma_extract/59316-59392.padding
  tests/integration/compression/uzip/zlib/__input__/myfs.img.uzip
  tests/integration/compression/uzip/zlib/__input__/myfs.padded.img.uzip
  tests/integration/compression/uzip/zlib/__output__/myfs.img.uzip_extract/0-59397.uzip
  tests/integration/compression/uzip/zlib/__output__/myfs.img.uzip_extract/0-59397.uzip_extract/0-59397
  tests/integration/compression/uzip/zlib/__output__/myfs.img.uzip_extract/59397-59904.padding
  tests/integration/compression/uzip/zlib/__output__/myfs.padded.img.uzip_extract/0-64.unknown
  tests/integration/compression/uzip/zlib/__output__/myfs.padded.img.uzip_extract/59461-60032.unknown
  tests/integration/compression/uzip/zlib/__output__/myfs.padded.img.uzip_extract/64-59461.uzip
  tests/integration/compression/uzip/zlib/__output__/myfs.padded.img.uzip_extract/64-59461.uzip_extract/64-59461
  tests/integration/compression/uzip/zstd/__input__/myfs.img.uzst
  tests/integration/compression/uzip/zstd/__output__/myfs.img.uzst_extract/0-58269.uzip
  tests/integration/compression/uzip/zstd/__output__/myfs.img.uzst_extract/0-58269.uzip_extract/0-58269
  tests/integration/compression/uzip/zstd/__output__/myfs.img.uzst_extract/58269-58368.padding
  uv.lock
Labels: enhancement, format:compression
